version: "3.8"

volumes:
  data:
  cloudbeaver:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"
  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    restart: always
    ports:
      - "5434:8978"
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
