version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "6543:8443"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /Library/Keychains:/Library/Keychains:rw
    environment:
      - JENKINS_OPTS=--prefix=/jenkins --httpsPort=8443 --httpsKeyStore=/Library/Keychains/jenkins.jks --httpsKeyStorePassword=jenkins
    networks:
      - jenkins_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8765:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins

networks:
  jenkins_network:

volumes:
  jenkins_home:
